#ifndef CPPCHALLENGER_GREATEST_COMMON_DIVISOR_H
#define CPPCHALLENGER_GREATEST_COMMON_DIVISOR_H

int greatest_common_divisor(int num_1, int num_2)
{
    return 0;
}

#endif //CPPCHALLENGER_GREATEST_COMMON_DIVISOR_H
